
WITH ST
as(

SELECT ANNEE, SUM(IIF(MT<0,1,0)) [NB CLIENT PNB NEGATIF],SUM(IIF(MT>0,1,0)) [NB CLIENT PNB POSITIF], SUM(IIF(MT=0,1,0)) [NB CLIENT PNB NULL],SUM(IIF(MT<0,1,1)) [NB CLIENT TOTAL],
SUM(IIF(MT<0,MT,0))[PNB NEGATIF] , SUM(IIF(MT>0,MT,0))[PNB POSITIF] ,SUM(IIF(MT=0,MT,0))[PNB NULL] ,SUM(MT)[PNB TOTAL]
FROM EXTRAC_IA_PNB_GLOBAL  
GROUP BY ANNEE)
SELECT *, 
CAST( CAST( [NB CLIENT PNB POSITIF] as decimal(18,2))/CAST([NB CLIENT TOTAL] as decimal(18,2))*100 as decimal(18,2)) [% CLIENT PNB POSITIF],
CAST( CAST( [NB CLIENT PNB NEGATIF] as decimal(18,2))/CAST([NB CLIENT TOTAL] as decimal(18,2))*100 as decimal(18,2)) [% CLIENT PNB NEGATIF],
CAST( CAST( [NB CLIENT PNB NULL] as decimal(18,2))/CAST([NB CLIENT TOTAL] as decimal(18,2))*100 as decimal(18,2)) [% CLIENT PNB NULL]

FROM ST ORDER BY ANNEE